name: 'Test Action'

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  test-action:
    name: 'Test Action'
    runs-on: ubuntu-latest

    steps:
      - name: 'Setup Repository (${{github.event.repository.name}})'
        uses: actions/checkout@v4
      
      - name: 'Test Action input'
        id: test
        uses: './'
        with:
          version: 'latest-snapshot'

      - name: 'Test Action output'
        run: |
          echo "Output: ${{ steps.test.outputs.json }}"
